export const flags ={
    'ar': require('./img/flags/ar.png'),
    'au': require('./img/flags/au.png'),
    'be': require('./img/flags/be.png'),
    'br': require('./img/flags/br.png'),
    'cm': require('./img/flags/cm.png'),
    'ca': require('./img/flags/ca.png'),
    'cr': require('./img/flags/cr.png'),
    'hr': require('./img/flags/hr.png'),
    'dk': require('./img/flags/dk.png'),
    'ec': require('./img/flags/ec.png'),
    'fr': require('./img/flags/fr.png'),
    'de': require('./img/flags/de.png'),
    'gh': require('./img/flags/gh.png'),
    'ir': require('./img/flags/ir.png'),
    'jp': require('./img/flags/jp.png'),
    'kr': require('./img/flags/kr.png'),
    'mx': require('./img/flags/mx.png'),
    'ma': require('./img/flags/ma.png'),
    'nl': require('./img/flags/nl.png'),
    'pl': require('./img/flags/pl.png'),
    'pt': require('./img/flags/pt.png'),
    'qa': require('./img/flags/qa.png'),
    'sa': require('./img/flags/sa.png'),
    'sn': require('./img/flags/sn.png'),
    'rs': require('./img/flags/rs.png'),
    'es': require('./img/flags/es.png'),
    'ch': require('./img/flags/ch.png'),
    'tn': require('./img/flags/tn.png'),
    'gb': require('./img/flags/gb.png'),
    'us': require('./img/flags/us.png'),
    'uy': require('./img/flags/uy.png'),
    'tbd': require('./img/flags/tbd.png'),
    'gb-wls': require('./img/flags/gb-wls.png')
}

export const rest = "http://192.168.1.11:3000/"